version: "3.9"

services:
  web:
    build: .
    container_name: cricket-dashboard-web
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    restart: unless-stopped
    networks:
      - app-network
    
  nginx:
    image: nginx:stable
    container_name: cricket-dashboard-nginx
    ports:
      - "8012:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/app.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    name: cricket-dashboard-network
